---

- name: command testing
  hosts: nxos-suw-lab
  connection: local
  gather_facts: no


  tasks:

    # Get CLI raw text output for a given command
    - nxos_command: command='show nve vni' host={{ inventory_hostname }} text=false type=show username={{ansible_ssh_user }} password={{ ansible_ssh_pass }}
      register: my_version

    - debug: var=my_version

